.\"                                      Hey, EMACS: -*- nroff -*-
.TH LUDEVIT_TK 1 "2006-11-04"
.SH NAME
ludev\('it_tk \- GUI frontend to the converter from standard Slovak into L. St\('ur version
.SH SYNOPSIS
.B ludev\('it_tk
.SH DESCRIPTION
This manual page documents the
.B ludev\('it
command.
.PP
\fBludev\('it\fP converts text from standard Slovak into the verion
designed by L. St\('ur. \fBludev\('it_tk\fP is a GUI frontend written in Python/Tkinter.

.SH NOTE
Due to technical restrictions, the program is actually
installed under the name \fBludevit_tk\fP. 

.SH AUTHOR
Radovan Garab\('ik <garabik @ kassiopeia.juls.savba.sk>


